name: tahsinv2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.4.2=py37_0
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.1=py37he30daa8_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - cryptography=3.0=py37hb09aad4_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.2=h5ab3b9f_0
  - htop=3.0.2=he28a2e2_0
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2020.1=217
  - isort=4.3.21=py37_0
  - jpeg=9b=h024ee3a_2
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libnl=3.2.25=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=he6710b0_1
  - mccabe=0.6.1=py37_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - olefile=0.46=py37_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pylint=2.5.3=py37_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-slugify=4.0.1=pyh9f0ad1d_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - text-unidecode=1.3=py_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchaudio=0.7.2=py37
  - tqdm=4.48.2=pyh9f0ad1d_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - unidecode=1.1.1=py_0
  - urllib3=1.24.3=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - albumentations==0.4.6
    - async-timeout==3.0.1
    - attrs==20.3.0
    - blessings==1.7
    - bottleneck-transformer-pytorch==0.1.2
    - cachetools==4.2.1
    - catalyst==20.12
    - click==7.1.2
    - colorama==0.4.4
    - colr==0.9.1
    - configparser==5.0.2
    - cycler==0.10.0
    - decorator==4.4.2
    - dill==0.3.3
    - docker-pycreds==0.4.0
    - docstring-parser==0.7.3
    - efficientnet-pytorch==0.6.3
    - einops==0.3.0
    - fire==0.4.0
    - fsspec==0.9.0
    - future==0.18.2
    - fvcore==0.1.3
    - gcc7==0.0.7
    - gitdb==4.0.5
    - gitpython==3.1.14
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - gpustat==0.6.0
    - grpcio==1.37.0
    - grpcio-tools==1.37.0
    - helpdev==0.7.1
    - imageio==2.9.0
    - imgaug==0.4.0
    - importlib-metadata==3.4.0
    - imutils==0.5.4
    - iniconfig==1.1.1
    - iopath==0.1.6
    - joblib==1.0.1
    - kaggle==1.5.12
    - kaptan==0.5.12
    - kiwisolver==1.3.1
    - labml==0.4.112
    - libtmux==0.8.5
    - markdown==3.3.4
    - matplotlib==3.3.4
    - minio==7.0.3
    - mpi4py==3.0.3
    - mpmath==1.2.1
    - multidict==5.1.0
    - multiprocess==0.70.11.1
    - munch==2.5.0
    - networkx==2.4
    - nibabel==3.2.1
    - ninja==1.10.0.post2
    - numpy==1.20.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencv-python==4.4.0.40
    - opencv-python-headless==4.5.1.48
    - p-tqdm==1.3.3
    - packaging==20.9
    - pandas==1.2.2
    - pathos==0.2.7
    - pathtools==0.1.2
    - pluggy==0.13.1
    - portalocker==2.2.1
    - pox==0.2.9
    - ppft==1.6.6.3
    - pretrainedmodels==0.7.4
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - py==1.10.0
    - py3nvml==0.2.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyqtgraph==0.11.1
    - pytest==6.2.2
    - python-graphviz==0.16
    - pytorch-gradcam==0.2.1
    - pytorch-lightning==1.2.8
    - pytorchcv==0.0.58
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - qdarkstyle==2.8.1
    - qtpy==1.9.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.16.12
    - ruamel-yaml-clib==0.2.2
    - scikit-image==0.17.2
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - sentry-sdk==1.0.0
    - setuptools==56.0.0
    - shapely==1.7.0
    - shortuuid==1.0.1
    - smmap==3.0.5
    - subprocess32==3.5.4
    - sympy==1.8
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - tifffile==2020.8.13
    - timm==0.4.5
    - tmuxp==1.7.2
    - torch==1.8.1
    - torchmetrics==0.2.0
    - torchsummary==1.5.1
    - torchvision==0.9.1
    - triton==1.0.0.dev20210330
    - utilitys==0.2.0
    - wandb==0.10.27
    - werkzeug==1.0.1
    - wheel==0.36.2
    - xmltodict==0.12.0
    - yacs==0.1.8
    - yarl==1.6.3
    - zipp==3.4.0
prefix: /home/UFAD/m.tahsinmostafiz/miniconda3/envs/tahsinv2
